version: '2'

services:
  json-server:
    image: node:latest
    working_dir: /json-server
    volumes:
      - ./json-server-folder:/json-server
    command: bash script.sh
    expose:
      - 8000

  lite-server:
    image: node:latest
    working_dir: /lite-server
    volumes:
      - ./lite-server-folder:/lite-server
    command: bash script.sh
    expose:
      - 3000

  nginx:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
    links:
      - json-server
      - lite-server

